### ISSUE TITLE
Add a skip configration option

### ISSUE THREAD

**Issue by zosrothko** [tomasbjerre/git-changelog-maven-plugin#12]
Please provde a clear description of your issue.
Add a `<configuration><skip>true|false</skip></configuration>` option in order to skip building a changelog in SNAPSHOT build for example.

**Comment by tomasbjerre** [comment]
Released in 1.61

**Comment by Opa-** [comment]
@tomasbjerre maybe use something more specific than just `skip` as this could clash with other plugin properties when running a `mvn foo bar -Dskip` ?

**Comment by tomasbjerre** [comment]
Not sure what you mean. You dont need to name the property skip. You can name it x and have <skip>${x}</skip> and do mvn -Dx=true

**Comment by Opa-** [comment]
You're damn right, I guess I was too tired when writing this 😝
