### ISSUE TITLE
Is possible to use a different branch than master to create the changelog

### ISSUE THREAD

**Issue by azuzi** [tomasbjerre/git-changelog-maven-plugin#13]
I would like to create a change log from something like a different branch called test. But here it always create the change-log from master.
Any possible solutions for this?

**Comment by tomasbjerre** [comment]
Yes there is fromRef and toRef

https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/1e915376f49759168375bfdd3750485986db15c6/git-changelog-maven-plugin-example/pom.xml#L212
