### ISSUE TITLE
maven release with tbhis plugin

### ISSUE THREAD

**Issue by eimarfandino** [tomasbjerre/git-changelog-maven-plugin#14]
Hi,

How do you use this plugin with the maven release? I get all the time that the file CHANGELOG have been modified

**Comment by eimarfandino** [comment]
thanks @tomasbjerre, so if i understand correctly you use the phase deploy in order to avoid the CHANGELOG modifications to make a failure during release:prepare?

**Comment by tomasbjerre** [comment]
I use the default ignore filter:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApiConstants.java#L11

So that the commits created by release-plugin will not change the changelog during release.

**Comment by eimarfandino** [comment]
problem i have is the following:
i make a change
i generate the changelog.md with the plugin (works great btw!)
commit to a branch(so this commit is not in the changelog file)
someone merge this branch into master and the release process starts
release fails because changelog file is modified

this last commit is not in the file then.... here is where the problem lies down

**Comment by tomasbjerre** [comment]
Can be solved by adding the plugin to a profile and only run it when that profile is active.

There is also a skip-attribute that you can set to a property. Set the property to true in pom.xml. run with mvn -Ppropertname=false when you want to generate changelog.

**Comment by eimarfandino** [comment]
ok thanks.  that is what i was thinking, just wanted to have this generation as part of the release process. 
keep up the good work! thanks
