### ISSUE TITLE
Goal not marked as Thread-safe

### ISSUE THREAD

**Issue by vhochstein** [tomasbjerre/git-changelog-maven-plugin#21]
Running  maven generate-sources I receive following Warning in log file

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following goals are not marked @threadSafe in apps2mce:
[WARNING] se.bjurr.gitchangelog:git-changelog-maven-plugin:1.63:git-changelog
[WARNING] *****************************************************************

**Comment by tomasbjerre** [comment]
Releasing fix now.

**Comment by vhochstein** [comment]
Thanks a lot, that was pretty fast. :-)
