### ISSUE TITLE
CLI Property has lower priority than pom property

### ISSUE THREAD

**Issue by vhochstein** [tomasbjerre/git-changelog-maven-plugin#26]
<configuration>
          <fromRef>HEAD</fromRef>
	<toRef>HEAD</toRef>
</configuration>

./mvnw -X  generate-resources -DfromRef=21.03.01.02 -DtoRef=21.03.01.03

My expectaction would be that cli parameter overrite maven config parameter values.

However actually HEAD is used as value for both parameters

**Comment by tomasbjerre** [comment]
How did you configure the plugin in your `pom.xml`? Perhaps if you change it to have properties for from/to, like this:

```xml
	<properties>
		<fromRef>HEAD</fromRef>
		<toRef>HEAD</toRef>
	</properties>

....
					<execution>
						<id>GenerateGitReleasenotes11</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>git-changelog</goal>
						</goals>
						<configuration>
							<file>RELEASENOTES.md</file>
							<fromRef>${fromRef}</fromRef>
							<toRef>${toRef}</toRef>
						</configuration>
					</execution>
```

**Comment by vhochstein** [comment]
yes using properties is working, thanks a lot for the hint
