### ISSUE TITLE
retrieving git log as plain text 

### ISSUE THREAD

**Issue by edeso** [tomasbjerre/git-changelog-maven-plugin#28]
hi,

currently looking for a way to retrieve the log text unescaped e.g
instead of
```
  &lt;repositories&gt;
```
plain text
```
  <repositories>
```
but do not seem to find a way. ist it possible? how? ..thanks!

**Comment by tomasbjerre** [comment]
You can avoid escaping by using triple { like this:

{{{violation.message}}}

**Comment by edeso** [comment]
thanks! did i miss the documentation somewhere?

also the result is now
```
2021-05-17 19:35:02 - Jukka Rahkonen - https://github.com/openjump-gis/openjump/commit/74c2c98582ff2bf
Add download link for OpenJUMP 2 snapshots

2021-05-17 15:09:17 - ed - https://github.com/openjump-gis/openjump/commit/860ec2c66770ddf
- minor rewording/reformatting
  - readded <timeSource>build</timeSource> in build-helper-maven-plugin,
  but deactivated it's execution m2e, cause it's not needed there and also
  chokes on timesource build
```
but i'd like the first comment line to be indented like the rest below. any way to achieve that?

**Comment by tomasbjerre** [comment]
The template is rendered with this lib:
https://github.com/jknack/handlebars.java

So that is where to look for these things

**Comment by edeso** [comment]
sorry! out of my depth here. are you saying there is no way to configure it as is? thx!

**Comment by tomasbjerre** [comment]
I dont know if it is possible. I guess this might be the pretty printing feature in Handlebars. It might be what causes the first indentation to be removed.

It is probably better to open an issue in their project.

**Comment by edeso** [comment]
no worries!

back to the other question. did i miss something in your examples about the non-escaping? didn't really find the documentaion as well btw.

still, great work! thanks!

**Comment by tomasbjerre** [comment]
No I dont think I have any example of that. You just need to know what to google. Try google "mustache disable escaping" and you will find it.

**Comment by edeso** [comment]
would you be opposed to a pull request that extends the example pom with a plain text version like i am in need of? just in case other might want it.

**Comment by tomasbjerre** [comment]
Such a pull request is welcome!
