### ISSUE TITLE
Enhance documentation for changelog.json file

### ISSUE THREAD

**Issue by M3lkior** [tomasbjerre/git-changelog-maven-plugin#3]
Hello @tomasbjerre , first, great job !

Is it possible to enhance/write the documentation for changelog.json file content ? no attributes are documented and it's difficult to know how to use them.

Thanks

**Comment by tomasbjerre** [comment]
Yes. Perhaps the json should be documented in the [library](https://github.com/tomasbjerre/git-changelog-lib).

More parameters can definitely be added to the maven plugin. And documented [here](https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/git-changelog-maven-plugin-example/pom.xml).

**Comment by tomasbjerre** [comment]
I added some documentation now, is that ok?

**Comment by tomasbjerre** [comment]
Also some more examples:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/git-changelog-maven-plugin-example/pom.xml

**Comment by M3lkior** [comment]
Yes, thanks
