### ISSUE TITLE
Is it possible to pass property from pom.xml to template file?

### ISSUE THREAD

**Issue by arboeh** [tomasbjerre/git-changelog-maven-plugin#38]
Is it possible to pass a property from pom.xml to the *.mustache-file?
I would like to extend the template with some values.

**Comment by tomasbjerre** [comment]
I think it works if you have the template within the pom. Does that solve your problem?
If you put the template within `<templateContent>`: https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/eb57be4b2933839c834052e5c307956832389d26/git-changelog-maven-plugin-example/pom.xml#L89

**Comment by arboeh** [comment]
Not really. I want to keep my pom as slim as possible, that's why I asked.
How would it be possible to add a property inside the template content part of the plugin? I would give it a try.
Btw: Thanks for your quick reply! 👍

**Comment by tomasbjerre** [comment]
If you try to use `<templateContent>` I think you can just put `${whatever.property.name}` within the template. Bu I'm not sure.

You may also have a look at the `extendedVariables` attribute that you can set in the pom and use in the template:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/eb57be4b2933839c834052e5c307956832389d26/src/main/java/se/bjurr/gitchangelog/plugin/GitChangelogMojo.java#L40

**Comment by arboeh** [comment]
I will try it tomorrow. Thanks!

**Comment by arboeh** [comment]
It's working. Thanks!
