### ISSUE TITLE
is it possible to only include commits with certain keywords?

### ISSUE THREAD

**Issue by wanghu001** [tomasbjerre/git-changelog-maven-plugin#39]
I noticed there is a configuration to ignore commits by setting the ignoreCommitsIfMessageMatches, but it would be nice if it is able to only include certain messages. 

BTW, I am interested in what is syntax of the template. Any direction would be appreciated.

**Comment by tomasbjerre** [comment]
Context of the template is documented here: https://github.com/tomasbjerre/git-changelog-lib

Syntax is Handlebars.

You can probably use negative lookahead in the regexp.
