### ISSUE TITLE
prependToFile 

### ISSUE THREAD

**Issue by wanghu001** [tomasbjerre/git-changelog-maven-plugin#41]
I love this plugin. I am going to adapt it to our projects. Noticed the prependToFile is available in git-changelog-lib, but not in its maven plugin. Is there any plan to make this option available in git-changelog-maven-plugin?

Thank you!

**Comment by tomasbjerre** [comment]
I added this feature now. Open issue again if not working!

**Comment by wanghu001** [comment]
Very nice. Thank you very much.
