### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by wanghu001** [tomasbjerre/git-changelog-maven-plugin#42]
Hi Tomas,

I am trying to build the git-changelog-lib and this plugin to new versions (1.166.0-custom and 1.92-custom) in my local. What I did were:
1. to build git-change-lib: I used 'gradle build'
2. to build plugin I used 'mvn clean install'

I have mvn 3.8.3 and Java 11.0.5. Both builds succeeded, but when I generate change log, I got:
[ERROR] Failed to execute goal se.bjurr.gitchangelog:git-changelog-maven-plugin:1.92-custom:git-changelog (GenerateGitChangelog_cc) on project private: Execution GenerateGitChangelog_cc of goal se.bjurr.gitchangelog:git-changelog-maven-plugin:1.92-custom:git-changelog failed: A required class was missing while executing se.bjurr.gitchangelog:git-changelog-maven-plugin:1.92-custom:git-changelog: com/google/gson/Gson
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>se.bjurr.gitchangelog:git-changelog-maven-plugin:1.92-custom
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/wanghu/.m2/repository/se/bjurr/gitchangelog/git-changelog-maven-plugin/1.92-custom/git-changelog-maven-plugin-1.92-custom.jar
[ERROR] urls[1] = file:/C:/Users/wanghu/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/C:/Users/wanghu/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[3] = file:/C:/Users/wanghu/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[4] = file:/C:/Users/wanghu/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[5] = file:/C:/Users/wanghu/.m2/repository/se/bjurr/gitchangelog/git-changelog-lib/1.166.0-custom/git-changelog-lib-1.166.0-custom.jar

Appreciate if you can help.
Hu

**Comment by tomasbjerre** [comment]
Perhaps something wrong with my build script. I would try running this in the library:
```
./gradlew clean build publishToMavenLocal -Pversion=custom-SNAPSHOT
```
And change this plugin to use version `custom-SNAPSHOT`.

**Comment by wanghu001** [comment]
Thanks a lot. Yes, this solves the build issue
