### ISSUE TITLE
updatePomWithNextSemanticVersionSuffixSnapshot config key does not validate under Maven + IDEA

### ISSUE THREAD

**Issue by unixunion** [tomasbjerre/git-changelog-maven-plugin#48]
The key updatePomWithNextSemanticVersionSuffixSnapshot appears to not be resolving under IDEA. So there is an annoying warning from IntelliJ about the schema being invalid. I am not sure, but I think the key needs to be exported from the mojo / plugin in order for IDEA to resolve it. 

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1773544/204227037-36f48c58-c413-424d-b568-047a28e9977a.png">

**Comment by tomasbjerre** [comment]
This is another goal, `<goal>semantic-version</goal>`, see the readme:
https://github.com/tomasbjerre/git-changelog-maven-plugin#update-version-based-on-conventional-commits
