### ISSUE TITLE
Add configuration "ignoreTagsIfNameMatches" to goal "semantic-version"

### ISSUE THREAD

**Issue by luvetter** [tomasbjerre/git-changelog-maven-plugin#49]
We have two kinds of tags in our repositories:

- One for the semantic version of the repository itself, like 2.0.1
- One for a "release version" that is the same in multiple repos and shows which versions should work togehter, this tags have the format "Year.RollingNumber", like 2023.03

The goal "semantic-version" recognizes the release-version as a semantiv version without a patch number and since the release version is usallay the newest tag in our repos it is used as "highst version" and as the base for the next semantic version. But we would like to ignore the tags with the format "Year.RollingNumber" in the semantic versioning process.

So we would like to set "ignoreTagsIfNameMatches" for the goal "semantic-version"

Example for minor update:

- Version is 2.0.1
- Tag "2.0.1", created at 26.02.2023
- Tag "2023.03", created at 27.02.2023

Current behaviour: 2.0.1 changes to 2023.4.0
Expected behaviour: 2.0.1 changes to 2.1.0 (through configuration of ignoreTagsIfNameMatches)

**Comment by tomasbjerre** [comment]
should be fixed now. Open issue again if any problems.
