### ISSUE TITLE
One line git commit messege

### ISSUE THREAD

**Issue by souzen** [tomasbjerre/git-changelog-maven-plugin#5]
Hi,
Is it possible to configure git-changelog to include only first line of git commit message in generated changelog?

**Comment by tomasbjerre** [comment]
I'm implementing this as some new variables:
* messageTitle (Only the first line of the message)
* messageBody (Everything, except the title)
* messageBodyItems (List of strings, the lines after the title)

A sample template here:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/test/resources/templates/testCommitsVariables.mustache

**Comment by tomasbjerre** [comment]
This is now in 1.14, should be in Maven Central within the hour. Open issue again if any problems.

**Comment by souzen** [comment]
Works great. Thank You
