### ISSUE TITLE
How to skip semantic-version goal

### ISSUE THREAD

**Issue by arkadioz** [tomasbjerre/git-changelog-maven-plugin#53]
I am using the Maven plugin, need to generate semantic-version, but I also need to skip this goal once I already have the version generated so that it does not execute anymore on further builds, have tried with skip tag set to true but it only skips the changelog generation goal, so I tried to separate goals in two different executions but found out that the semantic-version execution does not allow <skip> tag, is there a way to also skip the semantic-version generation?

My plugin config atm:

            <plugin>
                <groupId>se.bjurr.gitchangelog</groupId>
                <artifactId>git-changelog-maven-plugin</artifactId>
                <version>1.100.7</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>GenerateGitChangelog</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>git-changelog</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                            <templateContent>
                                # Changelog
                            </templateContent>
                            <file>CHANGELOG_GENERATED.md</file>
                        </configuration>
                    </execution>
                    <execution>
                        <id>GenerateSemanticVersion</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>semantic-version</goal>
                        </goals>
                        <configuration>
                            <updatePomWithCurrentSemanticVersionSuffixSnapshotIfNotTagged>false
                            </updatePomWithCurrentSemanticVersionSuffixSnapshotIfNotTagged>
                            <updatePomWithCurrentSemanticVersionSuffixSnapshot>false
                            </updatePomWithCurrentSemanticVersionSuffixSnapshot>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by tomasbjerre** [comment]
I added `skip` parameter in `1.101.0`. Open issue again if not working.
