### ISSUE TITLE
maven-release-plugin fails using v1.100.3+

### ISSUE THREAD

**Issue by Schlumpf9** [tomasbjerre/git-changelog-maven-plugin#60]
After upgrading from 1.100.3 to 1.100.6 or 2.0.0 I always receive the error 
`Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.1:prepare (default-cli) on project xy: 0.1.0-SNAPSHOT is invalid, expected a non-snapshot`

Is there something that has to be configured after updating to 1.100.6? With v1.100.3 everything worked.
Command i am using: `mvn -B -s ../settings.xml se.bjurr.gitchangelog:git-changelog-maven-plugin:1.100.6:semantic-version release:prepare -DpushChanges=false -Darguments=-DskipTests`

**Comment by tomasbjerre** [comment]
Try 2.0.1. Open issue again if not working.
