### ISSUE TITLE
gitchangelog generate changelog.md from first commit

### ISSUE THREAD

**Issue by Dhruva23** [tomasbjerre/git-changelog-maven-plugin#61]
Hi,

we are using gitchangelog plugin in jenkins free style job,  we selected choose from Reference "First Commit in repo", it generated huge changelog, if we go "A branch or tag" what variable we need to provide, we would like to generate changelog for single git lab tag.

Choose 'to' reference, if we select "A branch or tag" which git lab variable we need to provide.

**Comment by tomasbjerre** [comment]
Issues on the Jenkins plugin should be reported here:
https://github.com/jenkinsci/git-changelog-plugin/issues

I don't know the variablers contributed by a Gitlab plugin ([there are several such plugins](https://github.com/jenkinsci?q=gitlab&type=all&language=&sort=)). I cannot answer that.
