### ISSUE TITLE
Issue when using removeIssueFromMessage and settingFile

### ISSUE THREAD

**Issue by bobily156** [tomasbjerre/git-changelog-maven-plugin#9]
I noticed an issue when using the <settingFile> element. In the external config file I want to use 
'removeIssueFromMessage = true' , but doing so will not produce the intended outcome. If I remove  
'removeIssueFromMessage' from the jsaon file and move it back into the pom, the intended outcome is produced.

**Comment by bobily156** [comment]
looking into the base library looks like it should default to true but it is not

**Comment by tomasbjerre** [comment]
Should be fixed in 1.50.
